name: format

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  prettier:
    name: prettier --check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check formatting
        run: pnpm format:check
